### ISSUE TITLE
[BUG] Readme.md 에서 목차 링크 오류 

### ISSUE THREAD

**Issue by riyenas0925** [sejonginterface/Study-Python#1]
@haseungwon 
### 문제점
```1. [변수의 이해 및 기본 데이터 타입] (/.변수 이해 및 기본 데이터 타입)``` 이거를 다음과 같이 변경 ```1. [변수의 이해 및 기본 데이터 타입](https://github.com/sejonginterface/Study-Python)```

### 예시
1. [변수의 이해 및 기본 데이터 타입](https://github.com/sejonginterface/Study-Python)

**Comment by haseungwon** [comment]
체크 ㅋㅋ
